### ISSUE TITLE
请问xheditor上传图片会把地址转义 

### ISSUE THREAD

**Issue by kspt** [yaniswang/xhEditor#18]
链接也会转义
<a href="http://baidu.com">2222</a>

图片也是
<img src=upload/day_150906/201509061611368750.jpg alt=" " />

**Comment by yaniswang** [comment]
上传转义是什么意思？

**Comment by kspt** [comment]
就是当 我在编辑器里面上传了一张图片， 保存到数据库的时候 双引号 就会被斜杠转义
![1](https://cloud.githubusercontent.com/assets/13017039/9751129/8ada94cc-56d3-11e5-9606-d77e9ea9822d.png)

**Comment by kspt** [comment]
后来用笨方法 ，stripcslashes函数解决了。。。

**Comment by yaniswang** [comment]
你这个转义应该是PHP转的，网上搜下PHP相关，有大量文章介绍这个。
