### ISSUE TITLE
怎样才能保留html的中的<html>,<title>,<script> 内容。

### ISSUE THREAD

**Issue by twb0223** [yaniswang/xhEditor#25]
在使用编辑器 加载 一个完整的 html 页面源码时，为何自动过滤的  页面的 head，title，和包含的 script？

**Comment by yaniswang** [comment]
xhEditor不支持编辑完整的HTML代码，只支持编辑HTML片段。
编辑完整HTML，技术上会更复杂，目前暂时不支持。
