### ISSUE TITLE
IE11下粘贴文本，光标丢失

### ISSUE THREAD

**Issue by zc0519** [yaniswang/xhEditor#32]
希望作者能及时解决

**Comment by yaniswang** [comment]
很抱歉，这个项目已经不维护4年了

**Comment by zc0519** [comment]
您好！
 看到这条回复还是挺遗憾的，xheditor是我一个同事推荐的，他反应以前用的很好，所以这个项目中我一直在用，也用的还不错，昨天发现这个问题，您在这块是行家，能推荐下一直还不错的富文本编辑器吗？这个项目是政府项目，兼容IE8以上。谢谢了！

**Comment by yaniswang** [comment]
建议您使用kindeditor或者ckeditor
